package developer.com.mr.olx.ApiInterface;

import developer.com.mr.olx.clsApiClasses.ClsAddMobileDetails;
import developer.com.mr.olx.productsList.ClsInventoryMasterFormData;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.Multipart;
import retrofit2.http.POST;
import retrofit2.http.Part;

public interface InterfaceMobile {

    @POST("MobileInventoryMast/mobile_inventory_mast_save")
    Call<ClsAddMobileDetails> postAddMobile(@Body ClsAddMobileDetails obj);

    @Multipart
    @POST("MobileInventoryMast/mobile_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postMobileFormAPI(@Part("mo_inventory_id") RequestBody all_inventory_id,
                                                       @Part("user_id") RequestBody user_id,
                                                       @Part("mo_title") RequestBody mo_title,
                                                       @Part("brand_id") RequestBody brand_id,
                                                       @Part("model_name") RequestBody title,
                                                       @Part("mo_ram") RequestBody price,
                                                       @Part("mo_rom") RequestBody mo_rom,
                                                       @Part("mo_colour") RequestBody mo_colour,
                                                       @Part("mo_price") RequestBody mo_price,
                                                       @Part MultipartBody.Part mo_picture_link_1,
                                                       @Part MultipartBody.Part mo_picture_link_2,
                                                       @Part MultipartBody.Part mo_picture_link_3,
                                                       @Part MultipartBody.Part mo_picture_link_4,
                                                       @Part MultipartBody.Part mo_picture_link_5,
                                                       @Part MultipartBody.Part mo_picture_link_6,
                                                       @Part MultipartBody.Part mo_picture_link_7,
                                                       @Part MultipartBody.Part mo_picture_link_8,
                                                       @Part MultipartBody.Part mo_picture_link_9,
                                                       @Part MultipartBody.Part mo_picture_link_10,
                                                       @Part("mo_front_camera") RequestBody mo_front_camera,
                                                       @Part("mo_rear_camera") RequestBody mo_rear_camera,
                                                       @Part("mo_battery") RequestBody mo_battery,
                                                       @Part("mo_bill") RequestBody mo_bill,
                                                       @Part("mo_box") RequestBody mo_box,
                                                       @Part("mo_charger") RequestBody mo_charger,
                                                       @Part("mo_headset") RequestBody mo_headset,
                                                       @Part("mo_warranty") RequestBody mo_warranty,
                                                       @Part("insurance") RequestBody insurance,
                                                       @Part("i_description") RequestBody i_description,
                                                       @Part("show_mo_no") RequestBody show_mo_no,
                                                       @Part("description") RequestBody description,
                                                       @Part("location") RequestBody location,
                                                       @Part("latitude") RequestBody latitude,
                                                       @Part("longitude") RequestBody longitude,
                                                       @Part("cat_id") RequestBody cat_id,
                                                       @Part("sub_cat_id") RequestBody sub_cat_id);

    @Multipart
    @POST("BikeInventoryMast/bike_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postBikeScooterFormAPI(@Part("vehicle_inventory_id") RequestBody vehicle_inventory_id,
                                                            @Part("user_id") RequestBody user_id,
                                                            @Part("v_title") RequestBody v_title,
                                                            @Part("v_price") RequestBody v_price,
                                                            @Part MultipartBody.Part v_picture_link_1,
                                                            @Part MultipartBody.Part v_picture_link_2,
                                                            @Part MultipartBody.Part v_picture_link_3,
                                                            @Part MultipartBody.Part v_picture_link_4,
                                                            @Part MultipartBody.Part v_picture_link_5,
                                                            @Part MultipartBody.Part v_picture_link_6,
                                                            @Part MultipartBody.Part v_picture_link_7,
                                                            @Part MultipartBody.Part v_picture_link_8,
                                                            @Part MultipartBody.Part v_picture_link_9,
                                                            @Part MultipartBody.Part v_picture_link_10,
                                                            @Part("brand") RequestBody mo_front_camera,
                                                            @Part("kms") RequestBody kms,
                                                            @Part("year") RequestBody year,
                                                            @Part("insuarance") RequestBody insurance,
                                                            @Part("i_description") RequestBody i_description,
                                                            @Part("v_show_mo_no") RequestBody show_mo_no,
                                                            @Part("v_description") RequestBody description,
                                                            @Part("v_location") RequestBody location,
                                                            @Part("latitude") RequestBody latitude,
                                                            @Part("longitude") RequestBody longitude,
                                                            @Part("cat_id") RequestBody cat_id,
                                                            @Part("sub_cat_id") RequestBody sub_cat_id);

    @Multipart
    @POST("CarSell_InventoryMast/car_sell_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postCarSellFormAPI(@Part("car_sell_inventory_id") RequestBody car_sell_inventory_id,
                                                        @Part("user_id") RequestBody user_id,
                                                        @Part("car_title") RequestBody car_title,
                                                        @Part("car_brand_id") RequestBody car_brand_id,
                                                        @Part("car_model_name") RequestBody car_model_name,
                                                        @Part("c_owner") RequestBody c_owner,
                                                        @Part("year") RequestBody year,
                                                        @Part("c_registration") RequestBody c_registration,
                                                        @Part("c_km") RequestBody c_km,
                                                        @Part("c_price") RequestBody c_price,
                                                        @Part MultipartBody.Part c_picture_link_1,
                                                        @Part MultipartBody.Part c_picture_link_2,
                                                        @Part MultipartBody.Part c_picture_link_3,
                                                        @Part MultipartBody.Part c_picture_link_4,
                                                        @Part MultipartBody.Part c_picture_link_5,
                                                        @Part MultipartBody.Part c_picture_link_6,
                                                        @Part MultipartBody.Part c_picture_link_7,
                                                        @Part MultipartBody.Part c_picture_link_8,
                                                        @Part MultipartBody.Part c_picture_link_9,
                                                        @Part MultipartBody.Part c_picture_link_10,
                                                        @Part("year_of_registration") RequestBody year_of_registration,
                                                        @Part("c_colour") RequestBody c_colour,
                                                        @Part("engine_capacity") RequestBody engine_capacity,
                                                        @Part("mileage") RequestBody mileage,
                                                        @Part("car_fuel_id") RequestBody car_fuel_id,
                                                        @Part("transmission") RequestBody transmission,
                                                        @Part("c_insurance") RequestBody c_insurance,
                                                        @Part("i_description") RequestBody i_description,
                                                        @Part("c_show_mo_no") RequestBody c_show_mo_no,
                                                        @Part("c_description") RequestBody c_description,
                                                        @Part("c_location") RequestBody c_location,
                                                        @Part("latitude") RequestBody latitude,
                                                        @Part("longitude") RequestBody longitude,
                                                        @Part("cat_id") RequestBody cat_id,
                                                        @Part("sub_cat_id") RequestBody sub_cat_id);

    @Multipart
    @POST("CommVehicleInventoryMast/vehicle_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postCommVehicleFormAPI(@Part("vehicle_inventory_id") RequestBody vehicle_inventory_id,
                                                            @Part("user_id") RequestBody user_id,
                                                            @Part("v_title") RequestBody v_title,
                                                            @Part("v_price") RequestBody c_price,
                                                            @Part MultipartBody.Part v_picture_link_1,
                                                            @Part MultipartBody.Part v_picture_link_2,
                                                            @Part MultipartBody.Part v_picture_link_3,
                                                            @Part MultipartBody.Part v_picture_link_4,
                                                            @Part MultipartBody.Part v_picture_link_5,
                                                            @Part MultipartBody.Part v_picture_link_6,
                                                            @Part MultipartBody.Part v_picture_link_7,
                                                            @Part MultipartBody.Part v_picture_link_8,
                                                            @Part MultipartBody.Part v_picture_link_9,
                                                            @Part MultipartBody.Part v_picture_link_10,
                                                            @Part("v_type_id") RequestBody v_type_id,
                                                            @Part("brand") RequestBody brand,
                                                            @Part("kms") RequestBody kms,
                                                            @Part("year") RequestBody year,
                                                            @Part("insuarance") RequestBody insurance,
                                                            @Part("i_description") RequestBody i_description,
                                                            @Part("v_show_mo_no") RequestBody v_show_mo_no,
                                                            @Part("v_description") RequestBody v_description,
                                                            @Part("v_location") RequestBody v_location,
                                                            @Part("latitude") RequestBody latitude,
                                                            @Part("longitude") RequestBody longitude,
                                                            @Part("cat_id") RequestBody cat_id,
                                                            @Part("sub_cat_id") RequestBody sub_cat_id);

    @Multipart
    @POST("CarRentInventoryMast/car_rent_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postCarRentFormAPI(@Part("car_rent_inventory_id") RequestBody car_rent_inventory_id,
                                                        @Part("user_id") RequestBody user_id,
                                                        @Part("car_title") RequestBody car_title,
                                                        @Part("c_price") RequestBody c_price,
                                                        @Part MultipartBody.Part c_picture_link_1,
                                                        @Part MultipartBody.Part c_picture_link_2,
                                                        @Part MultipartBody.Part c_picture_link_3,
                                                        @Part MultipartBody.Part c_picture_link_4,
                                                        @Part MultipartBody.Part c_picture_link_5,
                                                        @Part MultipartBody.Part c_picture_link_6,
                                                        @Part MultipartBody.Part c_picture_link_7,
                                                        @Part MultipartBody.Part c_picture_link_8,
                                                        @Part MultipartBody.Part c_picture_link_9,
                                                        @Part MultipartBody.Part c_picture_link_10,
                                                        @Part("c_km_limit") RequestBody c_km_limit,
                                                        @Part("c_car_type") RequestBody c_car_type,
                                                        @Part("c_extra_charge") RequestBody c_extra_charge,
                                                        @Part("c_per_day_charge") RequestBody c_per_day_charge,
                                                        @Part("car_fuel_id") RequestBody car_fuel_id,
                                                        @Part("c_with_fuel") RequestBody c_with_fuel,
                                                        @Part("c_driver") RequestBody c_driver,
                                                        @Part("c_transmission") RequestBody c_transmission,
                                                        @Part("c_show_mo_no") RequestBody c_show_mo_no,
                                                        @Part("c_description") RequestBody c_description,
                                                        @Part("c_location") RequestBody c_location,
                                                        @Part("latitude") RequestBody latitude,
                                                        @Part("longitude") RequestBody longitude,
                                                        @Part("cat_id") RequestBody cat_id,
                                                        @Part("sub_cat_id") RequestBody sub_cat_id);


    @Multipart
    @POST("PropertyInventorySellMast/property_inventory_sell_mast_save")
    Call<ClsInventoryMasterFormData> postPropertySellFormAPI(@Part("property_inventory_id") RequestBody property_inventory_id,
                                                             @Part("user_id") RequestBody user_id,
                                                             @Part("p_title") RequestBody p_title,
                                                             @Part("p_type_id") RequestBody p_type_id,
                                                             @Part("p_name") RequestBody p_name,
                                                             @Part("p_bedroom") RequestBody p_bedroom,
                                                             @Part("p_bathroom") RequestBody p_bathroom,
                                                             @Part("p_sq_ft") RequestBody p_sq_ft,
                                                             @Part("p_price") RequestBody p_price,
                                                             @Part MultipartBody.Part p_picture_link_1,
                                                             @Part MultipartBody.Part p_picture_link_2,
                                                             @Part MultipartBody.Part p_picture_link_3,
                                                             @Part MultipartBody.Part p_picture_link_4,
                                                             @Part MultipartBody.Part p_picture_link_5,
                                                             @Part MultipartBody.Part p_picture_link_6,
                                                             @Part MultipartBody.Part p_picture_link_7,
                                                             @Part MultipartBody.Part p_picture_link_8,
                                                             @Part MultipartBody.Part p_picture_link_9,
                                                             @Part MultipartBody.Part p_picture_link_10,
                                                             @Part("p_furnishing_id") RequestBody p_furnishing_id,
                                                             @Part("p_car_parking_id") RequestBody p_car_parking_id,
                                                             @Part("p_sup_builtup_area") RequestBody p_sup_builtup_area,
                                                             @Part("p_carpet_area") RequestBody p_carpet_area,
                                                             @Part("p_listed_by_id") RequestBody p_listed_by_id,
                                                             @Part("p_status_id") RequestBody p_status_id,
                                                             @Part("p_maintenance") RequestBody p_maintenance,
                                                             @Part("p_show_mo_no") RequestBody p_show_mo_no,
                                                             @Part("p_description") RequestBody p_description,
                                                             @Part("p_location") RequestBody p_location,
                                                             @Part("latitude") RequestBody latitude,
                                                             @Part("longitude") RequestBody longitude,
                                                             @Part("cat_id") RequestBody cat_id,
                                                             @Part("sub_cat_id") RequestBody sub_cat_id);


    @Multipart
    @POST("PropertyInventoryRentMast/property_inventory_rent_mast_save")
    Call<ClsInventoryMasterFormData> postPropertyRentFormAPI(@Part("property_inventory_id") RequestBody property_inventory_id,
                                                             @Part("user_id") RequestBody user_id,
                                                             @Part("p_title") RequestBody p_title,
                                                             @Part("p_type_id") RequestBody p_type_id,
                                                             @Part("p_name") RequestBody p_name,
                                                             @Part("p_bedroom") RequestBody p_bedroom,
                                                             @Part("p_bathroom") RequestBody p_bathroom,
                                                             @Part("p_sq_ft") RequestBody p_sq_ft,
                                                             @Part("p_price") RequestBody p_price,
                                                             @Part MultipartBody.Part p_picture_link_1,
                                                             @Part MultipartBody.Part p_picture_link_2,
                                                             @Part MultipartBody.Part p_picture_link_3,
                                                             @Part MultipartBody.Part p_picture_link_4,
                                                             @Part MultipartBody.Part p_picture_link_5,
                                                             @Part MultipartBody.Part p_picture_link_6,
                                                             @Part MultipartBody.Part p_picture_link_7,
                                                             @Part MultipartBody.Part p_picture_link_8,
                                                             @Part MultipartBody.Part p_picture_link_9,
                                                             @Part MultipartBody.Part p_picture_link_10,
                                                             @Part("p_furnishing_id") RequestBody p_furnishing_id,
                                                             @Part("p_car_parking_id") RequestBody p_car_parking_id,
                                                             @Part("p_sup_builtup_area") RequestBody p_sup_builtup_area,
                                                             @Part("p_carpet_area") RequestBody p_carpet_area,
                                                             @Part("p_listed_by_id") RequestBody p_listed_by_id,
                                                             @Part("p_preferred_renters_id") RequestBody p_preferred_renters_id,
                                                             @Part("p_maintenance") RequestBody p_maintenance,
                                                             @Part("p_show_mo_no") RequestBody p_show_mo_no,
                                                             @Part("p_description") RequestBody p_description,
                                                             @Part("p_location") RequestBody p_location,
                                                             @Part("latitude") RequestBody latitude,
                                                             @Part("longitude") RequestBody longitude,
                                                             @Part("cat_id") RequestBody cat_id,
                                                             @Part("sub_cat_id") RequestBody sub_cat_id);

    @Multipart
    @POST("JobInventoryMast/job_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postJobFormAPI(@Part("job_inventory_id") RequestBody job_inventory_id,
                                                    @Part("user_id") RequestBody user_id,
                                                    @Part("j_title") RequestBody j_title,
                                                    @Part("from_salary") RequestBody from_salary,
                                                    @Part("to_salary") RequestBody to_salary,
                                                    @Part MultipartBody.Part j_picture_link_1,
                                                    @Part MultipartBody.Part j_picture_link_2,
                                                    @Part MultipartBody.Part j_picture_link_3,
                                                    @Part MultipartBody.Part j_picture_link_4,
                                                    @Part MultipartBody.Part j_picture_link_5,
                                                    @Part MultipartBody.Part j_picture_link_6,
                                                    @Part MultipartBody.Part j_picture_link_7,
                                                    @Part MultipartBody.Part j_picture_link_8,
                                                    @Part MultipartBody.Part j_picture_link_9,
                                                    @Part MultipartBody.Part j_picture_link_10,
                                                    @Part("j_type_id") RequestBody j_type_id,
                                                    @Part("s_p_id") RequestBody s_p_id,
                                                    @Part("p_type_id") RequestBody p_type_id,
                                                    @Part("j_designation") RequestBody j_designation,
                                                    @Part("j_show_mo_no") RequestBody j_show_mo_no,
                                                    @Part("j_description") RequestBody j_description,
                                                    @Part("j_location") RequestBody j_location,
                                                    @Part("latitude") RequestBody latitude,
                                                    @Part("longitude") RequestBody longitude,
                                                    @Part("cat_id") RequestBody cat_id,
                                                    @Part("sub_cat_id") RequestBody sub_cat_id);

    @Multipart
    @POST("OfficeInventoryMast/office_inventory_mast_save")
    Call<ClsInventoryMasterFormData> postOfficeFormAPI(@Part("office_inventory_id") RequestBody office_inventory_id,
                                                       @Part("user_id") RequestBody user_id,
                                                       @Part("o_title") RequestBody o_title,
                                                       @Part("p_type_id") RequestBody p_type_id,
                                                       @Part("p_name") RequestBody p_name,
                                                       @Part("cabin") RequestBody cabin,
                                                       @Part("washroom") RequestBody washroom,
                                                       @Part("o_sq_ft") RequestBody o_sq_ft,
                                                       @Part("o_price") RequestBody o_price,
                                                       @Part MultipartBody.Part o_picture_link_1,
                                                       @Part MultipartBody.Part o_picture_link_2,
                                                       @Part MultipartBody.Part o_picture_link_3,
                                                       @Part MultipartBody.Part o_picture_link_4,
                                                       @Part MultipartBody.Part o_picture_link_5,
                                                       @Part MultipartBody.Part o_picture_link_6,
                                                       @Part MultipartBody.Part o_picture_link_7,
                                                       @Part MultipartBody.Part o_picture_link_8,
                                                       @Part MultipartBody.Part o_picture_link_9,
                                                       @Part MultipartBody.Part o_picture_link_10,
                                                       @Part("p_furnishing_id") RequestBody p_furnishing_id,
                                                       @Part("p_car_parking_id") RequestBody p_car_parking_id,
                                                       @Part("o_sup_builtup_area") RequestBody o_sup_builtup_area,
                                                       @Part("o_carpet_area") RequestBody o_carpet_area,
                                                       @Part("p_listed_by_id") RequestBody p_listed_by_id,
                                                       @Part("employee_capacity") RequestBody employee_capacity,
                                                       @Part("o_maintenance") RequestBody o_maintenance,
                                                       @Part("o_show_mo_no") RequestBody o_show_mo_no,
                                                       @Part("o_description") RequestBody o_description,
                                                       @Part("o_location") RequestBody o_location,
                                                       @Part("latitude") RequestBody latitude,
                                                       @Part("longitude") RequestBody longitude,
                                                       @Part("cat_id") RequestBody cat_id,
                                                       @Part("sub_cat_id") RequestBody sub_cat_id);

}


